name: TMDB

options:
  minimumXcodeGenVersion: 2.10
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "17.0"

settings:
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"

targets:

  TMDBTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      INFOPLIST_FILE: TMDB/Info.plist
    sources: [TMDBTests]
    dependencies:
      - target: TMDB
      
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: TMDBTests
          parallelizable: true
          randomExecutionOrder: true

  TMDB:
    type: application 
    platform: iOS
    deploymentTarget: 17.0
    sources: [TMDB]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "br.com.TMDB"
      INFOPLIST_FILE: TMDB/Info.plist
      MARKETING_VERSION: 1.0.0